services:
  - type: web
    name: ai-engineering-api
    env: python
    plan: free
    branch: main
    root: ai-engineering-bootcamp-v2/week-1v2
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: ai-engineering-streamlit
    env: python
    plan: free
    branch: main
    root: ai-engineering-bootcamp-v2/week-1v2
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: sh start_streamlit.sh
